### ISSUE TITLE
the input file --accessions

### ISSUE THREAD

**Issue by ZhaoyanZhong** [symgenoevolab/SyntenyFinder#2]
It is a very nice software. I tried it and had a question: does the input file --accessions have to be accessions for annotated chromosome-level genomes on NCBI? If we have assembled the genome and have not uploaded it to NCBI, how can we use it as an input file to execute the software?

**Comment by ijyliao** [comment]
Thank you for your interest in our software! The automated command line version of SyntenyFinder only takes chromosome-level annotated genomes from NCBI, but our python notebook is much more flexible and can accommodate a wider range of intake formats. To access this, please download the directory ```SyntenyFinder_customisable``` and run ```Synteny_main.ipynb``` by following the commented instructions. I plan on making a more comprehensive tutorial for this moving forward, but in the meantime, let me know if you have any questions! 
Cheers, 
Isabel

**Comment by hhzhao713** [comment]
I'm having the same problem, is there an easy way to do synteny with my own data? How do I use synteny_main.ipynb？
